name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build
        run: |
          mvn --batch-mode --update-snapshots -Pwindows,!linux clean compile package
          cp -rf ./target/Kasimaps.jar ./dist/Kasimaps.jar
          mvn --batch-mode --update-snapshots -Plinux,!windows clean compile package
          cp -rf ./target/Kasimaps_lnx.jar ./dist/Kasimaps_lnx.jar
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ./dist/Kasimaps.jar
          git add ./dist/Kasimaps_lnx.jar
          git commit -am "automatic build"
          git push