name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build windows
        run: mvn --batch-mode --update-snapshots -Pwindows,!linux clean compile package
      - name: Commit & Push windows
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ./target/Kasimaps.jar
          git commit -am "Add windows distribution"
          git push
      - name: Build linux
        run: mvn --batch-mode --update-snapshots -Plinux,!windows clean compile package
      - name: Commit & Push linux
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ./target/Kasimaps_lnx.jar
          git commit -am "Add linux distribution"
          git push